version: 2

python:
  version: 3.7
  system_packages: true
  install:
    - requirements: requirements.txt
    - requirements: docs/requirements_doc.txt

sphinx:
  configuration: docs/conf.py

formats: all
